FROM	debian:11

RUN	apt update -y && apt upgrade -y && apt-get install -y mariadb-server

COPY	conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

COPY	conf/setup.sh /usr/local/bin/setup.sh

RUN	chmod +x /usr/local/bin/setup.sh

EXPOSE	3306

ENTRYPOINT	["setup.sh"]
